### ISSUE TITLE
CSIS Demo for European Week of Regions and Cities

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#105]
This is the status of the studies we are preparing for automated screening (HC-LE and impact calculation with EMIKAT) and basic / "poor man's" screening (showing some European-level pre-calculated data only).

### Agios Dimitrios
Advanced Screening Study: In theory, there should be UA data available for HC-LE and Heat Hazard Impact Calculation, but it's not yet on ATOS Geoserver. Therefore no automated screening is possible ATM. We are waiting for @negroscuro to make the data for ATHINA available.

- [x] Study: [Advanced Screening Agios Dimitrios](https://csis.myclimateservice.eu/study/35) (study id: 35, EMIKAT id: 3189)
- [x] City / Region: [ATHINA](https://csis.myclimateservice.eu/taxonomy/term/1788)
- [x] EEA City Profile: [ATHINA](https://tableau.discomap.eea.europa.eu/t/Aironline/views/2019_Urban_vulnerability_links/mainpage?iframeSizedToWindow=false&%3Aembed=y&%3AshowAppBanner=false&%3Adisplay_count=yes&%3AshowVizHome=yes&%3Atoolbar=yes&City_param=Athina)
- [x] HC data: [available](https://csis.myclimateservice.eu/study/35/step/1530/view/table)
- [x] HC Twins [available](https://csis.myclimateservice.eu/study/35/step/1530/view/twins), but partially [broken](https://github.com/clarity-h2020/docker-drupal/issues/81#issuecomment-535470278)
- [x] HC-LE **Input** data (UA layers): [available](https://csis.myclimateservice.eu/study/35/step/1524/view/maps)
- [x] HC-LE data [available](https://csis.myclimateservice.eu/study/35/step/1524/view/table)
- [x] EE Data: [available](https://csis.myclimateservice.eu/study/35/step/1529/view/table)
- [x] EE Twins: [available](https://csis.myclimateservice.eu/study/35/step/1529/view/twins), but partially [broken](https://github.com/clarity-h2020/docker-drupal/issues/81#issuecomment-535470278)
- [x] RA-IA Data [available](https://csis.myclimateservice.eu/study/35/step/1528/view/table)
- [x] Scenario Analysis App: [available](https://csis.myclimateservice.eu/study/35/step/1528/view/scenario-analysis)
- [x] IAO: [available](https://csis.myclimateservice.eu/study/35/step/1526/view/table)
- [x] Adaptation Twins: [available](https://csis.myclimateservice.eu/study/35/step/1526/view/twins)
- [x] EEA City Profile App: [available](https://csis.myclimateservice.eu/study/35/step/1525/view/external)
- [x] PDF Report: [available](https://csis.myclimateservice.eu/print/pdf/group/35)

### Alba Iulia
Advanced Screening Study should be possible right now: UA data is available for HC-LE and Heat Hazard Impact Calculation, but there seems to be a [problem](https://github.com/clarity-h2020/emikat/issues/20#issuecomment-535432501)) in the back-end. We are waiting for @humerh to fix this. 

- [x] Study: [Advanced Screening Alba Iulia](https://csis.myclimateservice.eu/study/33) (study id: 33, EMIKAT id: 3209)
- [x] City / Region: [ALBA_IULIA](https://csis.myclimateservice.eu/taxonomy/term/2212)
- [x] EEA City Profile: [Alba Iulia](https://tableau.discomap.eea.europa.eu/t/Aironline/views/2019_Urban_vulnerability_links/mainpage?iframeSizedToWindow=false&%3Aembed=y&%3AshowAppBanner=false&%3Adisplay_count=yes&%3AshowVizHome=yes&%3Atoolbar=yes&City_param=Alba%20Iulia)
- [x] HC data: [available](https://csis.myclimateservice.eu/study/33/step/1519/view/table)
- [x] HC Twins [available](https://csis.myclimateservice.eu/study/33/step/1519/view/twins), but partially [broken](https://github.com/clarity-h2020/docker-drupal/issues/81#issuecomment-535470278)
- [x] HC-LE **Input** data (UA layers): [available](https://csis.myclimateservice.eu/study/33/step/1513/view/maps)
- [x] HC-LE data [available](https://csis.myclimateservice.eu/study/33/step/1513/view/table)
- [x] EE Data: [available](https://csis.myclimateservice.eu/study/33/step/1518/view/table)
- [x] EE Twins: [available](https://csis.myclimateservice.eu/study/33/step/1518/view/twins), but partially [broken](https://github.com/clarity-h2020/docker-drupal/issues/81#issuecomment-535470278)
- [x] RA-IA Data [available](https://csis.myclimateservice.eu/study/35/step/1530/view/table)
- [x] Scenario Analysis App: [available](https://csis.myclimateservice.eu/study/33/step/1517/view/scenario-analysis)
- [x] IAO: [available](https://csis.myclimateservice.eu/study/35/step/1526/view/table)
- [x] Adaptation Twins: [available](https://csis.myclimateservice.eu/study/35/step/1526/view/twins)
- [x] EEA City Profile App: [available](https://csis.myclimateservice.eu/study/33/step/1514/view/external)
- [x] PDF Report: [available](https://csis.myclimateservice.eu/print/pdf/group/33)

### Bottrop, Arnsberg and Dortmund

No HC-LE input layers are available for those cities, that means, we cannot perform a screening study. In this case, the user could only perform a "Basic Screening Study", that is, a study without any HC-LE or Impact Calculation. In such a study, we can show Hazard + Exposure (if available, unfortunately population exposure is only available from EMIKAT). That means, we have to

- [x] create and configure new study type "[Basic Screening Study](https://csis.myclimateservice.eu/taxonomy/study-type/basic-screening)"
- [ ] create a copy of the European Wide Data Package as **"Basic Screening" Data Package** without any HC-LE or EMIKAT Screening result layers. 

In the new "Basic" Data Package, instead of our own processed UA Layers, we could simply include some [general UA layers]( https://land.copernicus.eu/local/urban-atlas/urban-atlas-2012) from (e.g. as Exposure) and also some layers from EEA's Urban Adaptation Map Viewer (see also https://github.com/clarity-h2020/csis/issues/60). 

But before addressing this we first have to fix the remaining issues for Agios Dimitrios and Alba Iulia. Unless somebody else takes the lead and takes care about the new **"Basic Screening" Data Package**.

**Comment by p-a-s-c-a-l** [comment]
Status Update:

**Comment by p-a-s-c-a-l** [comment]
Status Update: 
- HC-LE **Input** Data for ATHINA now available, as well as HC-LE data, but no RA/IA data
- still no HC-LE data for Alba Iulia
- Scenario Analysis App needs a [new view](https://github.com/clarity-h2020/emikat/issues/9#issuecomment-536445460)

**Comment by p-a-s-c-a-l** [comment]
@humerh OK, now we are just missing [impact results](https://csis.myclimateservice.eu/study/35/step/1528/view/table) for Agios Dimitrios [from EMIKAT](https://service.emikat.at/EmiKatTst/api/scenarios/3189/feature/view.2975/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Frequent%27&filter=SZ_ID%3D3189) and [aggregated results](https://github.com/clarity-h2020/emikat/issues/9#issuecomment-536445460) for scenario analysis.

**Comment by humerh** [comment]
The total population for the motality rate calculation was missing in the statistic. I used the numbers of another year.
So the calculation was possible.

**Comment by DenoBeno** [comment]
I have published these two studies, so that we can find them easily.

![image](https://user-images.githubusercontent.com/2961790/65985152-86809a80-e481-11e9-9ba7-14e5e655992f.png)

**Comment by p-a-s-c-a-l** [comment]
Scenario Analysis is now available again. ATM we compare all Emissions Scenario / Time Period combinations. This will change when Adaptation Scenarios become available. There is no criteria function and ranking function available yet. Mortality rate (‰) is already a qualitative value , so it's not so important now. It becomes more interesting, when there a different (economic?!) indicators to compare.

![grafik](https://user-images.githubusercontent.com/1788226/66048401-be431d00-e529-11e9-8eb6-df65127f4bcc.png)

**Comment by DenoBeno** [comment]
![image](https://user-images.githubusercontent.com/2961790/66053202-2c8bdd80-e532-11e9-8319-3d08841a5076.png)

RPC 26 has higher mortality than RPC 45 and 85 for "rare" events. That doesn't look plausible to me.

**Comment by p-a-s-c-a-l** [comment]
> RPC 26 has higher mortality than RPC 45 and 85 for "rare" events. That doesn't look plausible to me

It depends. We don't know what the rare events are (duration and max. temperature). This information is not available here, so it's not possible to tell whether its plausible or not.

**Comment by claudiahahn** [comment]
In case it is still possible to show something for Bottrop and other cities without ESM data, here is a suggestion for the basic data package: the following urban atlas classes could be extracted (and grouped together) and displayed as separate layers (or potentially also together in one map): 
![grafik](https://user-images.githubusercontent.com/45260352/66127355-b8ae0b80-e5eb-11e9-987d-aea8c50a5d2b.png)

**Comment by claudiahahn** [comment]
To give you an idea how this classification compares to the model results, I have made some screenshots.
![grafik](https://user-images.githubusercontent.com/45260352/66127520-2e19dc00-e5ec-11e9-964a-6d0be4433f32.png)

![grafik](https://user-images.githubusercontent.com/45260352/66127547-3eca5200-e5ec-11e9-9aea-689de5e8022c.png)

**Comment by claudiahahn** [comment]
It would probably good to provide figures like that in CSIS, such that the user gets a better idea. If you intend to use these figures / to integrate them, let me know. Then I'll make a proper legend etc.

**Comment by claudiahahn** [comment]
And I agree with Pascal, that it would be great to include some layers from EEA's Urban Adaptation Map Viewer (see also #60) - to identify where the most vulnerable people are (children under 5, people 75 years old or older, lone-pensioner households)

**Comment by DenoBeno** [comment]
> In case it is still possible to show something for Bottrop and other cities without ESM data, here is a suggestion for the basic data package: the following urban atlas classes could be extracted (and grouped together) and displayed as separate layers (or potentially also together in one map):
> ![grafik](https://user-images.githubusercontent.com/45260352/66127355-b8ae0b80-e5eb-11e9-987d-aea8c50a5d2b.png)

If I understand it correctly, you are proposing to produce a new layer (either in advance or on the fly by EMIKAT) that would simply take the land cover information and map it into something like 0-10 scale where each number corresponds to a "heating potential". Then show a color-coded map with low values corresponding to blue, then going over green, yellow to red?

That sounds like a relatively easy thing to do.

**Comment by claudiahahn** [comment]
I would just take the land use classes listed above and display 5 layers (very high warm-up potential, high warm-up potential, good cooling potential, coolest places and very high to low warm-up potential) and leave everything else not classified. That gives the user the possibility to quickly see where hot spots are likely to occur and where rather cool places are.  If one displays the red and yellow layers at once, the map would look like the upper left figure in my examples. 
A color ramp is not ideal, because of classes like "airport"/ "port" / "industrial, commercial, public, military and private units", which can either warm-up extremely or not much at all, depending on the degree of soil sealing and on the location.
I don't think it is necessary to use Emikat for that.

**Comment by DenoBeno** [comment]
Hm, for this we would need a possibility to show several layers at once and also to have each of the layers color coded differently on a map. I will add this as a wish for future improvements of teh map component (for discussion) at https://github.com/clarity-h2020/map-component/issues/59

**Comment by DenoBeno** [comment]
This is the result of my testing of the prototype as it is today

[Advanced Screening Agios Dimitrios.pdf](https://github.com/clarity-h2020/csis/files/3692530/Advanced.Screening.Agios.Dimitrios.pdf)

**Comment by DenoBeno** [comment]
Apparently, all the tables are showing the same data. At least they do for the two studies I looked at here: https://github.com/clarity-h2020/table-components/issues/20

**Comment by p-a-s-c-a-l** [comment]
> here is a suggestion for the basic data package:

I don't assume that $sombody worked on this basic data package? So it's not there. Nothing to show for Bottrop, sorry.

> the following urban atlas classes could be extracted (and grouped together) and displayed as separate layers (or potentially also together in one map):

This is something @negroscuro has to comment on. If this data is available, we could simple create new (grouped) layers and add them as [background layers](https://github.com/clarity-h2020/data-package/issues/4) to the Data Package.

> I don't think it is necessary to use Emikat for that.

I agree.

> Hm, for this we would need a possibility to show several layers at once and also to have each of the layers color coded differently on a map.

This is a server side feature (layer groups) supported by Geoserver. On client side you cannot change the colours of WMS layers. Rendering, grouping and styling is done by the server, the client just shows the final image.

**Comment by DenoBeno** [comment]
Demo went well, so we could close this issue. I'm busy writing down the recommendations. In general:

- the ideas of the workflow and project templates and external applications and report generation are great and seem to be mostly working now.
- concentrate on presenting the data in a better way. e.g. 

For maps: better color coding, possibility to see the data values on/next to a map, ideally also a possibility to see the "diff" between two layers
For tables: less data, more useful data.
