### ISSUE TITLE
Populate CKAN with metadata from datasets

### ISSUE THREAD

**Issue by maesbri** [clarity-h2020/csis#11]
This tasks relates to the creation of the "Catalogue of local data sources and sample datasets" (D2.2). It depends on the following tasks:

- [x] [Collect and document data sources](https://github.com/clarity-h2020/csis/issues/9)
- [x] [Install CKAN Extensions](https://github.com/clarity-h2020/ckan/issues/1)
- [x] [Configure CKAN for CSIS](https://github.com/clarity-h2020/ckan/issues/2)

This task is connected to
- [Install Rasdaman and configure some initial raster layers](https://github.com/clarity-h2020/csis/issues/10)
- [Configure the CSIS with some datasets](https://github.com/clarity-h2020/csis/issues/12)

**Comment by ghilbrae** [comment]
We were not aware that this has been already decided, as I asked about this on last weeks devels telco and no one gave me an answer.

Anyway, we'll be writing to all DC leaders so they can start introducing their metadata.

@p-a-s-c-a-l can you give us the url to our instance for this email?

Thanks!

**Comment by ghilbrae** [comment]
@p-a-s-c-a-l we have decided to start with this. 

The idea is that every partner should be responsible of their own data. Do you agree with us creating a user for each partner involved in this? Is there anything we should take into account before doing this?
Thanks!!

**Comment by p-a-s-c-a-l** [comment]
@ghilbrae 
I've configured the SMTP server. Emails are now sent from noreply@csis.myclimateservice.eu

**Comment by p-a-s-c-a-l** [comment]
done

**Comment by Gauravp-NEC** [comment]
@p-a-s-c-a-l How did you configure the SMTP server.I am also getting the same error when I am trying to create a new user using their email via the Add Member button in an organization. 

"Error sending the invite email, the user was not created: SMTP server could not be connected to: "localhost" [Errno 99] Cannot assign requested address"

**Comment by p-a-s-c-a-l** [comment]
@Gauravp-NEC You can change the [email settings](https://docs.ckan.org/en/ckan-2.7.3/maintaining/configuration.html#email-settings) in [CKAN configuration file](https://docs.ckan.org/en/ckan-2.7.3/maintaining/configuration.html#ckan-configuration-file).

**Comment by Gauravp-NEC** [comment]
@p-a-s-c-a-l  Thank you for response.
I am beginner in ckan. Do I need to install SMTP Server on my local machine?
