### ISSUE TITLE
Meta issue: User/Group Permissions and roles

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/csis#114]
We need to configure the necessary user roles, so that we can let real users try out the CSIS.

**Related issues:** [115](https://github.com/clarity-h2020/docker-drupal/issues/115), [82](https://github.com/clarity-h2020/docker-drupal/issues/82)

### What needs to be done on the (Drupal) User level:

- [x]  authenticated users (so everyone with an account) can create Screening Studies

- [x] authenticated users with the role "Expert" can additionally create Expert Studies

- [x] ~define which user roles will be allowed to create new showcases, twins, adaptation options etc.~ Showcases, Twins, Solution offers will be created in the marketplace and then syncronized with the CSIS. So no users beside admins will be allowed to directly create them in the CSIS. (See this [issue](https://github.com/clarity-h2020/marketplace/issues/20#event-2962978088))

- [ ] anonymous users should be able to see everything in a **published** study, but they cannot change anything (similar to the "Observer" group role) 

### What needs to be done on the Group-membership level:

- [x] person who creates a Study automatically becomes the **Owner** role assigned

- [x] only **Owner** can add other authenticated users to the Study and make them either a team-member or an observer or even another (Co-)Owner

- [x] **Team** members should be able to create own report images and edit & delete them (aka be able to play around in all the GL-steps)

- [x] only the **Owner** should be able to edit fundamental settings like the study type, study area, selected data package etc. (so everything that is in the Study step)

- [x] **Observers** can only see everything inside the study but not add or change anything

- [x] ~tbc...~ additional group roles will added when needed

**Comment by patrickkaleta** [comment]
> * only the **Owner** should be able to edit fundamental settings like the study type, study area, selected data package etc. (so everything that is in the Study step)

This one is a bit tricky. Permissions are already set and its working, but....
For the Edit-buttons in the **Context** and **Data** tabs we use DisplaySuite token fields (containing the links to the individual form modes). But these fields are then always displayed in the tab no matter what permissions the user has. And since we open those forms in modals, we don't even get a decent "Access denied" message on the screen, but only a error message in the console... ☹️ 

To actually hide those buttons for user that cannot access the edit forms, I will have to adapt the csis helpers module and hide those buttons if the `write_permissions` attribute in the **studyInfo** object is 0.

**Comment by DenoBeno** [comment]
It might be easier to hide the whole step?

**Comment by patrickkaleta** [comment]
> It might be easier to hide the whole step?

Do you mean hiding the whole Study step or just the substeps Context and Data? Hiding the whole Study step would be possible by not allowing member to view the group, but then they will have no idea, who is part of the study team, which data package has been selected and other basic settings...

Hiding just the two substeps would be less dramatic, since all the information from those substeps can still be viewed in the Summary substep, but I'm not aware of a way to hide individual display modes of a Group display. Also, we would have to make the navigation bar group-role dependent and I'm not sure this can be done in a View?

**Comment by patrickkaleta** [comment]
> > * only the **Owner** should be able to edit fundamental settings like the study type, study area, selected data package etc. (so everything that is in the Study step)
> 
> This one is a bit tricky. Permissions are already set and its working, but....
> For the Edit-buttons in the **Context** and **Data** tabs we use DisplaySuite token fields (containing the links to the individual form modes). But these fields are then always displayed in the tab no matter what permissions the user has. And since we open those forms in modals, we don't even get a decent "Access denied" message on the screen, but only a error message in the console... ☹️
> 
> To actually hide those buttons for user that cannot access the edit forms, I will have to adapt the csis helpers module and hide those buttons if the `write_permissions` attribute in the **studyInfo** object is 0.

This is done now. I created a new [JS](https://github.com/clarity-h2020/csis-helpers-module/commit/0240a93a2a5d15d9d970853f168f3a5d1192c62e#diff-bb3ac41ade361d8eb8090c4b3abe636f) within the CSIS helpers module, which we can from now on use for permission related issues.
<br>

**Just a short explanation of how it works:** 
- In the Display Suite a created a special CSS class, which can be selected in the Display mode of the entity
- that CSS selector is used by the JavaScript to identify elements for which the permission check should be performed
- if the write_permission attribute in the $studyObject is set to 0, then the JavaScript hides the element and the user cannot be confused by it anymore

**Comment by patrickkaleta** [comment]
So if you're now not part of the Study group, you won't see the edit buttons in the Study step. However, this will now also hide those buttons for administrators, so I'll implement a bypass.

**Comment by Andrea4ad** [comment]
Hi,
want to **report** something from the **perspective of a user** without special rights just stumbling into this tool... 
- I logged in with single-sign on
- selected Solution Offers
- got a table with offers from the Clarity sphere - _could scroll down, but there is no 2nd page or so_
I know as a fact that somebody added solutions from outside the Clarity sphere, nr. 42, 43, 44
I wanted to have a look at them, but they are not in the table. 
I can enter the URL directly (because I happen to know the number) and then I get there, it´s not a matter of rights. Anyway, a user should have **acces** to stuff like that **via the GUI**, so it´s a bug and not a feature ;)

**Comment by DenoBeno** [comment]
if we need some kind of QA, we could do something similar to DRIVER+ PoS.
Users can add data at any time, but admin can overrule their publication
and hide it...

**Comment by patrickkaleta** [comment]
Regarding user/group permissions all urgent tasks are done.

For now, only question remaining is, which user roles will be allowed to create **showcases**, **adaptation options**, **twins** (and probably more?)

This needs to be addressed at some point (currently the 3 mentioned entities above can be created by **admins** and **editors**), but it is IMHO not urgent right now. Changing priority to **low**.

**Comment by p-a-s-c-a-l** [comment]
Can this be closed? I don't think that any external non-admin users will create any showcases, adaptation options, or twins. User-generated content now going in to marketplace.

**Comment by patrickkaleta** [comment]
No, I'm afraid we still need to decide whether or not anonymous users should really be able to see all published studies or just a couple of selected ones (the demonstrator cases for example).

**Comment by patrickkaleta** [comment]
This can be closed. In the [settings](https://csis.myclimateservice.eu/admin/config/csis_helpers/default) of the csis_helpers module admins can select which published Studies should be accessible to anonymous users.
