### ISSUE TITLE
Prepare CSIS Acceptance Tests

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#133]
We have to perform acceptance tests to ensure that our "minimal viable product" is "fit for purpose", that is, it delivers the proposed value.

Each partner must name two persons from its organization to perform the testing of the [public CSIS](). We must prepare a bullet point of actions that the user has to test. We use this GitHub issue as a first step to collect the appointed tester names. Then we create a separate issue for each organisation. If the tester encounters any problem a comment should be added to the respective issue.

**Tasks:**
- [ ] collect tester names
- [ ] define test specification 
- [ ] create individual issues

**List of Testers:**

Organisation | Tester 1 | Tester 2
-- | -- | --
AIT |   |  
ATOS |   |  
CIS |   |  
SMHI |   |  
METEOGRID |   |  
ZAMG |   |  
LUPT-PLINIVS |  
StockCity |   |  
EUREKA |   |  
NAPOLI |   |  
AEMET |   |  
WSP |   |  
ACCIONA |   |  
SCC |   |  
CABJOM |   |  
CEDEX |   |  
LINZ |   |

**Comment by LenaStr** [comment]
LenaStr will test for SMHI.

**Comment by p-a-s-c-a-l** [comment]
> LenaStr will test for SMHI.

And who's the second person from SMHI ? :-)

**Comment by LenaStr** [comment]
We will see, still discussions. Måns and Anki will test for CabJon, but Måns had problems understanding how to access GitLab.

**Comment by manslindell** [comment]
Trying to put my username in....hmmmm, can't edit. Working on it!

**Comment by claudiahahn** [comment]
claudiahahn and  RobAndGo will test for ZAMG
