### ISSUE TITLE
Prepare CSIS BETA Release

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#145]
Here collect all **SHOWSTOPPER** issues that **must** be resolved in order to make a public release of CSIS. Sure, we can work with [Milestones](https://github.com/clarity-h2020/csis/milestones) and the [Project Board](https://github.com/orgs/clarity-h2020/projects/2), but this additional issue gives the high priority tasks more visibility.

In this regard, I want to close also all issues that don't have much chance of becoming implemented (YAGNI, KISS) . This will help us to keep focused on our still realistic goal to go live with the system as it is now, even if it's not perfect. 

- [x] [CSIS Production Cloud Infrastructure](https://github.com/clarity-h2020/csis/issues/113)
- [x] *[Include in Report Functionality broken](https://github.com/clarity-h2020/csis-helpers-module/issues/9)* (beyound repair?!)
- [x] **[New EMIKAT calculation currently not possible](https://github.com/clarity-h2020/emikat/issues/33)**
- [x] [Issues with new study step templates in CSIS](https://github.com/clarity-h2020/csis/issues/150)
- [x] [Allow Emikat calculation tests to be run by the UI testing service](https://github.com/clarity-h2020/csis/issues/153)
- [x] [Replace automated study triggering with a dedicated "(re)calculate" button](https://github.com/clarity-h2020/emikat/issues/34)
- [x] **[Scientific Validation of Screening Results](https://github.com/clarity-h2020/emikat/issues/35)**
- [x] [Please test and if needed calibrate the local temperature estimates](https://github.com/clarity-h2020/emikat/issues/24)
- [x] [Height correction for (Temperature) local effects](https://github.com/clarity-h2020/emikat/issues/32)
- [x] [Provide a way to import/export/syncronize content ](https://github.com/clarity-h2020/csis/issues/135)
- [x] [Allow visitors to see (some) studies](https://github.com/clarity-h2020/csis/issues/130)
- [ ] [Clean up the System](https://github.com/clarity-h2020/docker-drupal/issues/125)
- [x] [Basic European Wide Data Package for Basic Screening Studies](https://github.com/clarity-h2020/data-package/issues/65)
- [x] [New style for CSIS CLARITY theme](https://github.com/clarity-h2020/clarity-theme/issues/17)
- [x] [Export Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/23) 
- [ ] [Update CLARITY GeoServer URIs](https://github.com/clarity-h2020/data-package/issues/66)
- [x] [SingleSignOn fails on users](https://github.com/clarity-h2020/docker-drupal/issues/140)
- [x] [Usability Showstoppers](https://github.com/clarity-h2020/docker-drupal/issues/141)
- [x] [Include In Report Button not working properly](https://github.com/clarity-h2020/csis-helpers-module/issues/9)
- [x] [Service Monitoring with Cachet](https://github.com/clarity-h2020/csis-technical-validation/issues/7)
- [x] [Google Maps API Key expired](https://github.com/clarity-h2020/docker-drupal/issues/146)
- [x] [Reliable Country Selection](https://github.com/clarity-h2020/docker-drupal/issues/145)

**Comment by p-a-s-c-a-l** [comment]
#### Status:
- [ ] [Scientific Validation of Screening Results](https://github.com/clarity-h2020/emikat/issues/35): **ongoing**
- [ ] [Provide a way to import/export/syncronize content ](https://github.com/clarity-h2020/csis/issues/135): *done*?
- [ ] [Clean up the System](https://github.com/clarity-h2020/docker-drupal/issues/125): **tbd** (unpublish content)
- [ ] [Basic European Wide Data Package for Basic Screening Studies](https://github.com/clarity-h2020/data-package/issues/65): **in progress**. Basic screening studies untested
- [ ] [Usability Showstoppers](https://github.com/clarity-h2020/docker-drupal/issues/141): *done*
- [ ] [Export Geoserver layers from MTG to ATOS](https://github.com/clarity-h2020/ckan/issues/23): *should be done* but some open questions unanswered 
- [ ] [Update CLARITY GeoServer URIs](https://github.com/clarity-h2020/data-package/issues/66): **tbd**
- [ ] [Reliable Country Selection](https://github.com/clarity-h2020/docker-drupal/issues/145): **in progress**
- [ ] [Google Maps API Key expired / Twins](https://github.com/clarity-h2020/docker-drupal/issues/146): **stalled**

**Comment by p-a-s-c-a-l** [comment]
done
