### ISSUE TITLE
Perform CSIS Beta Release

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis#162]
In this issue we plan the [CSIS BETA Release](https://github.com/clarity-h2020/csis/issues/145). We have to define a time frame when all people are available needed for release preparation so that we can minimise the downtime of csis.myclimateservice.eu

### Release Preparation
Resolve remaining issues:
- [x] @DanielRodera [New geoserver (geoserver.myclimateservice.eu) uses different layer name](https://github.com/clarity-h2020/data-package/issues/67)
- [x] @therter [Update CLARITY GeoServer URIs in Data Packages](https://github.com/clarity-h2020/data-package/issues/66)
- [x] @humerh [Update CLARITY GeoServer URIs in EMIKAT](https://github.com/clarity-h2020/emikat/issues/38)

### Perform Release
- [x] @p-a-s-c-a-l Notify users about expected downtime
- [x] @p-a-s-c-a-l shutdown containers on V3LS1809 and copy to csis.ait.ac.at and csis-dev.ait.ac.at, start containers
- [x] @patrickkaleta / @fgeyer16 make sure that content on **csis**.ait.ac.at is read-only except for creating new studies
- [x] @patrickkaleta / @fgeyer16 disable everything on the DEV system **csis-dev**.ait.ac.at that may interferes with the PROD system on **csis**.ait.ac.at (EMIKAT Trigger, Transport Application triggers, SSO?!, ...)
- [ ] @patrickkaleta / @fgeyer16 if possible check the synchronisation from DEV -> PROD. Be sure to sync from csis-dev.ait.ac.at (62.218.164.246) to csis.ait.ac.at (62.218.164.247).
- [x] @p-a-s-c-a-l update reverse proxy config on V3LS1809 and forward csis.myclimateservice.eu to csis.ait.ac.at

### ~~Test Release with proxied csis.myclimateservice.eu~~
nginx on csis.myclimateservice.eu (V3LS1809) now redirects to csis.ait.ac.at (62.218.164.247) until DNS entries are updated. This *should* work with EMIKAT Triggers and Drupal API requests (e.g. performed by Map Component)
- [ ] ~~@patrickkaleta Update Drupal on csis.ait.ac.at and change site domain to csis.myclimateservice.eu~~ 
- [ ] ~~@patrickkaleta Create and test an automated screening study on csis.myclimateservice.eu~~
- [ ] ~~@p-a-s-c-a-l Test external apps (Map, Table, Scenario Analysis)~~
- [x] @DanielRodera change DNS entry of **csis**.myclimateservice.eu to 62.218.164.247. (Note: csis-dev.myclimateservice.eu is already on 62.218.164.246)

### Test Release with csis.myclimateservice.eu
DNS changes may take some time, so this will be done the other day:
- [x] @p-a-s-c-a-l shutdown reverse proxy on V3LS1809
- [x] @p-a-s-c-a-l Update reverse proxy config on csis.ait.ac.at and renew certificates of csis.myclimateservice.eu
- [x] @p-a-s-c-a-l Create and test an automated screening study on csis.myclimateservice.eu
- [ ] @p-a-s-c-a-l Notify users

For performing the release we need at least @p-a-s-c-a-l and @patrickkaleta / @fgeyer16. If we are able to resolve the remaining issues asap, we should be able to perform the release right after the next WPL telco on Tuesday 02.06. Otherwise we have to set-up another telco.

@DanielRodera Please talk to your IT department in advance so that they are **prepared** to change the DNS entry of csis.myclimateservice.eu. The actual change can be initiated when we've successfully tested the system with proxied csis.myclimateservice.eu.

**Comment by DanielRodera** [comment]
> @DanielRodera Please talk to your IT department in advance so that they are prepared to change the DNS entry of csis.myclimateservice.eu. The actual change can be initiated when we've successfully tested the system with proxied csis.myclimateservice.eu.

Our IT people are already warned and prepared to do the change on your command.

**Comment by patrickkaleta** [comment]
@fgeyer16 and I will further talk about the open actions for this issue on Thursday. He'll look into the CAS/SSO before that if possible.

In the meantime it's still possible to login directly into either PROD or DEV instance if necessary (e.g. for admins) by directly visiting the individual login pages:
https://csis.ait.ac.at/user/login
https://csis-dev.ait.ac.at/user/login

**Comment by p-a-s-c-a-l** [comment]
https://csis.myclimateservice.eu/ and https://csis-dev.myclimateservice.eu/ are now available. Sites are put in maintenance mode until remaining steps have been resolved.

**Comment by ghilbrae** [comment]
Hi! To access the csis-dev can we use the same user/pass that we have been using up until now?

**Comment by patrickkaleta** [comment]
> Hi! To access the csis-dev can we use the same user/pass that we have been using up until now?

Yes, usernames and passwords are still the same. If you have problems with your credentials, let me know.

**Comment by patrickkaleta** [comment]
> [ ] @patrickkaleta / @fgeyer16 disable everything on the DEV system **csis-dev**.ait.ac.at that may interferes with the PROD system on **csis**.ait.ac.at (EMIKAT Trigger, Transport Application triggers, SSO?!, ...)

Configuration of the [csis_helpers module](https://github.com/clarity-h2020/csis-helpers-module) for the **DEV <-> PROD** setup is now complete. 

Emikat trigger, TM trigger and Emikat-Testing trigger are only active for `https://csis.myclimateservice.eu/` as the Host URL. For the DEV environment or any local CSIS instances, those triggers will not fire and instead a log message will be written to the [Drupal-intern Log report](https://csis.myclimateservice.eu/admin/reports/dblog).

Besides the csis_helpers module I don't have anything (cronjobs, etc..) that could interfere with our DEV <-> PROD setup. Still pending is now the SSO, which will hopefully be done by @fgeyer16 today.

**Comment by patrickkaleta** [comment]
> Still pending is now the SSO, which will hopefully be done by @fgeyer16 today.

SSO is now disabled on the DEV system.

**Comment by patrickkaleta** [comment]
> * @patrickkaleta / @fgeyer16 if possible check the synchronisation from DEV -> PROD. Be sure to sync from csis-dev.ait.ac.at (62.218.164.246) to csis.ait.ac.at (62.218.164.247).

This is planned for tommorrow (around noon).

**Comment by p-a-s-c-a-l** [comment]
> **Impact:** We will have to handle user permissions on the PROD server manually! This is manageable.

O.K., so what does this mean for our [acceptance tests](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification#walkthrough)? If a user creates a new account, is manual intervention needed before he/she can perform a new screening study?

**Comment by p-a-s-c-a-l** [comment]
>   @humerh [Update CLARITY GeoServer URIs in EMIKAT](https://github.com/clarity-h2020/emikat/issues/38)

What is the status here?

**Comment by patrickkaleta** [comment]
> > **Impact:** We will have to handle user permissions on the PROD server manually! This is manageable.
> 
> O.K., so what does this mean for our [acceptance tests](https://github.com/clarity-h2020/csis-technical-validation/wiki/Acceptance-Test-Specification#walkthrough)? If a user creates a new account, is manual intervention needed before he/she can perform a new screening study?

No, thankfully not. Permissions are handled on a (user-)**ROLE** level. Any new user account will get the permissions set automatically based on the (user-)roles that this account is given.

Manual intervention will be needed if we create new content types and need to decide what kind of permissions will be necessary for it (make it read-only on PROD? Maybe just allow changes to it on PROD by Editors? etc.)

**Comment by p-a-s-c-a-l** [comment]
> This is planned for tommorrow (around noon).

FYI: @therter updated the [cities script](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) which should be run during synchronisation to update the cities taxonomy with cities [having HC-LE data available](https://geoserver.myclimateservice.eu/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Acity&bbox=1969465.0%2C996016.875%2C7168551.0%2C4677889.0&width=768&height=543&srs=EPSG%3A3035&format=application/openlayers). ATM the selection box contains [all cities](https://github.com/clarity-h2020/csis-technical-validation/issues/45#issuecomment-639312636) allowing the user to choose a city which is not supported yet. This problem should be resolved after synchronisation.

**Comment by patrickkaleta** [comment]
I'm trying to push the latest changes in the configuration to our private gitlab repository, but I'm getting the following error:
`error: failed to push some refs to 'git@gitlab.atosresearch.eu:ari/clarity-csis-drupal.git'`

Screenshot:
![git-push-error](https://user-images.githubusercontent.com/42167036/83862484-4a918980-a722-11ea-9a21-4b1855b59636.png)

@p-a-s-c-a-l how did you manage to push changes to our private repository? Can maybe somebody from ATOS help out? @maesbri or @DanielRodera?

**Comment by p-a-s-c-a-l** [comment]
on which instance?

**Comment by p-a-s-c-a-l** [comment]
imho @maesbri has to unlock the ip

**Comment by patrickkaleta** [comment]
> on which instance?

on the DEV instance

**Comment by patrickkaleta** [comment]
@maesbri or @DanielRodera can you please check the security settings for the [private Gitlab repository](https://gitlab.atosresearch.eu/ari/clarity-csis-drupal/tree/dev). 

We need to be able to push/pull changes from our new DEV and PROD servers to this repository in order to perform config/content synchronizations between those two servers.

**Comment by maesbri** [comment]
I am checking it now with our IT. I'll let you know asap when it is fixed.

**Comment by patrickkaleta** [comment]
New repository also not working (getting a "connection timed out" error). I've created a separate [issue](https://github.com/clarity-h2020/docker-drupal/issues/150) for that now.

As discussed today, I will now instead move the necessary yaml configuration files manually and run the import for our cities/regions taxonomy, so that the City selection box will only contain "working" cities.

**Comment by patrickkaleta** [comment]
Countries and Cities/Regions have been successfully synchronized! ATM **12 out of 43** Countries and **20 out of 455** Cities/Regions can be used in the CSIS.

@therter's [republish script](https://github.com/clarity-h2020/docker-drupal/blob/dev/scripts/republish.sh) is now available on the DEV server (under `/home/patrick/`) and executable (had to install zip and unzip modules on the DEV server for that purpose).

**Just to clarify:** I **ONLY** synchronized the Countries and Cities/Regions. For properly synchronizing configuration and remaining content, I'm now waiting for the [private Git repository issue](https://github.com/clarity-h2020/docker-drupal/issues/150) to be fixed first.

If it becomes necessary to synchronize other content in the meantime, let me know and I'll do it manually.

**Comment by p-a-s-c-a-l** [comment]
done :-)
